"""SPECTRA shared schema package.

Every cross-service contract lives here.  Services depend on these models, not
on each other's internals, which is what keeps ingestion / search / agent /
models / graph / UI independently replaceable.
"""

from .catalog import (
    Asset,
    Chunk,
    IndexVersion,
    IngestJob,
    SearchHistoryEntry,
    SourceDescriptor,
    SourceHealth,
)
from .entities import (
    CanonicalEntity,
    EntityLink,
    EntityMention,
    EntityResolution,
    ResolutionCandidate,
)
from .enums import (
    AssetKind,
    EntityType,
    JobStatus,
    Modality,
    ModelRole,
    ModelState,
    Role,
    SearchMode,
    SourceStatus,
    SourceType,
)
from .ids import (
    asset_id,
    call_id,
    case_id,
    chunk_id,
    claim_id,
    content_hash,
    entity_id,
    evidence_id,
    investigation_id,
    job_id,
    mention_id,
    new_id,
    object_uri,
    step_id,
)
from .provenance import (
    AudioLocator,
    DatabaseLocator,
    DocumentLocator,
    ExternalLocator,
    ImageLocator,
    Locator,
    Provenance,
    VideoLocator,
    format_timestamp,
    parse_locator,
)
from .retrieval import (
    RetrievalStageStat,
    ScoreBreakdown,
    SearchFilters,
    SearchHit,
    SearchRequest,
    SearchResponse,
)
from .runtime import (
    GPUStatus,
    HealthReport,
    ModelCandidate,
    ModelEvent,
    ModelInfo,
    ModelRuntimeStatus,
)
from .security import ANONYMOUS, ROLE_CAPABILITIES, SYSTEM, PermissionContext

__all__ = [
    "ANONYMOUS",
    "Asset",
    "AssetKind",
    "AudioLocator",
    "CanonicalEntity",
    "Chunk",
    "DatabaseLocator",
    "DocumentLocator",
    "EntityLink",
    "EntityMention",
    "EntityResolution",
    "EntityType",
    "ExternalLocator",
    "GPUStatus",
    "HealthReport",
    "ImageLocator",
    "IndexVersion",
    "IngestJob",
    "JobStatus",
    "Locator",
    "Modality",
    "ModelCandidate",
    "ModelEvent",
    "ModelInfo",
    "ModelRole",
    "ModelRuntimeStatus",
    "ModelState",
    "PermissionContext",
    "Provenance",
    "ROLE_CAPABILITIES",
    "ResolutionCandidate",
    "RetrievalStageStat",
    "Role",
    "SYSTEM",
    "ScoreBreakdown",
    "SearchFilters",
    "SearchHistoryEntry",
    "SearchHit",
    "SearchMode",
    "SearchRequest",
    "SearchResponse",
    "SourceDescriptor",
    "SourceHealth",
    "SourceStatus",
    "SourceType",
    "VideoLocator",
    "asset_id",
    "call_id",
    "case_id",
    "chunk_id",
    "claim_id",
    "content_hash",
    "entity_id",
    "evidence_id",
    "format_timestamp",
    "investigation_id",
    "job_id",
    "mention_id",
    "new_id",
    "object_uri",
    "parse_locator",
    "step_id",
]
